# fly.toml app configuration file generated for global-nexus-institute-api-v1 on 2024-10-29T13:21:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'global-nexus-institute-api-v1'
primary_region = 'cdg'
machines = false

[build]

[http_service]
  internal_port = 5000
  force_https = true

[resources]
  memory = "1024"
  cpu_kind = "shared"
  cpus = 1